
export const FORGOT_PASSWORD_REQUEST = 'app/ForgotPasswordPage/FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'app/ForgotPasswordPage/AUTHENTICATE_RESET_PASSWORD_TOKEN_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'app/ForgotPasswordPage/AUTHENTICATE_RESET_PASSWORD_TOKEN_ERROR';
