/* eslint-disable no-multi-spaces */

export const REMOVE_LOGGED_USER = 'App/REMOVE_LOGGED_USER';

export const SET_LOADING_STATE  = 'App/SET_LOADING_STATE';
export const SET_ERROR_STATE    = 'App/SET_ERROR_STATE';
export const SET_USER_STATE     = 'App/SET_USER_STATE';

export const AUTHENTICATE_FROM_TOKEN = 'App/AUTHENTICATE_FROM_TOKEN';
export const AUTHENTICATE_FROM_TOKEN_SUCCESS = 'App/AUTHENTICATE_FROM_TOKEN_SUCCESS';
export const AUTHENTICATE_FROM_TOKEN_ERROR = 'App/AUTHENTICATE_FROM_TOKEN_ERROR';

