
export const RESET_PASSWORD_REQUEST = 'app/ResetPasswordPage/RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'app/ResetPasswordPage/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'app/ResetPasswordPage/RESET_PASSWORD_ERROR';
export const AUTH_RESET_PASSWORD_TOKEN = 'app/ResetPasswordPage/AUTH_RESET_PASSWORD_TOKEN';
export const AUTH_RESET_PASSWORD_TOKEN_SUCCESS = 'app/ResetPasswordPage/AUTH_RESET_PASSWORD_TOKEN_SUCCESS';
export const AUTH_RESET_PASSWORD_TOKEN_ERROR = 'app/ResetPasswordPage/AUTH_RESET_PASSWORD_TOKEN_ERROR';
